---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: networking-oss-deployments
  - name: toolsmiths-metadata-dir
    optional: true
  - name: routing-release
  - name: routing-release-ci

outputs:
  - name: cipher-manifest

run:
  path: routing-release-ci/ci/tasks/generate-cipher-manifest/task

params:
  CIPHERS:
  OUTPUT_DIR: cipher-manifest
  ENVIRONMENT:
