---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
- name: routing-release
- name: routing-release-ci

outputs:
  - name: perf-manifest

run:
  path: routing-release-ci/ci/tasks/generate-perf-manifest/task

params:
  MANIFEST_PATH:
  ROUTING_RELEASE_DIR: routing-release
  OUTPUT_DIR: perf-manifest
