---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
- name: release
- name: routing-release-ci

outputs:
- name: modified-release

params:
  # comma-separated values of folders in src to run update in
  PACKAGES_TO_UPDATE:
  # Identity to use for the git commit
  GIT_COMMIT_USERNAME: "CF Routing Team CI Bot"
  GIT_COMMIT_EMAIL: "cf-routing-eng@pivotal.io"

run:
  path: routing-release-ci/ci/tasks/upgrade-dep-dependencies-in-release/task
